In [6]:
import torch
import copy
from torch.nn import functional as F
import torch.nn as nn

In [14]:
net = nn.Sequential(
    nn.Conv2d(6, 9, )
)
for i, (name, param) in enumerate(net.named_parameters()):
    print(name, param, '\n=====================')

0.weight Parameter containing:
tensor([[0.9167],
        [0.3254]], requires_grad=True) 
0.bias Parameter containing:
tensor([-0.2514, -0.4472], requires_grad=True) 
2.weight Parameter containing:
tensor([[-0.1024, -0.0273],
        [ 0.6416,  0.6693],
        [-0.5635,  0.6806]], requires_grad=True) 
2.bias Parameter containing:
tensor([-0.5677, -0.4745, -0.1256], requires_grad=True) 


In [ ]:
net2 = copy.deepcopy(net)
